### ISSUE TITLE
DMRemoteRequest In Swift

### ISSUE THREAD

**Issue by Trifusion** [davidmuzi/DMRemoteRequest#1]
Love this code! Any chance you could port a version to swift?

Thanks

Greg

**Comment by davidmuzi** [comment]
I have no plans for porting to Swift, but I suspect a bridging header should be sufficient

**Comment by Trifusion** [comment]
Ya now that I look at it closer it will need a bridge, was hoping it could be done in all swift.

Thanks for posting your code.

Greg
